# 线性代数

## 线性代数的实现
标量由只有一个元素的张量表示

In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

你可以将向量视为标量组成的列表

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一元素

In [3]:
x[3]

tensor(3)

访问张量的长度

In [4]:
len(x)

4

只有一个轴的张量，形状只有一个元素。

In [5]:
x.shape

torch.Size([4])

通过指定两个分量$m$和$n$来创建一个形状为$m×n$的矩阵

In [6]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

*对称矩阵*(symmetric matrix)$A$等于其转置:$A = A^T$

In [8]:
B = torch.tensor([[1, 2, 3], [2, 0, 4],[3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据。

In [10]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [11]:
A = torch.arange(20, dtype = torch.float32).reshape(5,4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵按元素乘法称为*哈达玛积*（Hadamard product) 

In [12]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [13]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape  #每个元素加a

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

计算元素的和

In [14]:
x = torch.arange(4, dtype = torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和

In [15]:
A = torch.arange(20).reshape(5, 4)
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190))

In [36]:
A = torch.arange(2 * 20).reshape(2, 5, 4)
A, A.shape, A.sum()

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19]],
 
         [[20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31],
          [32, 33, 34, 35],
          [36, 37, 38, 39]]]),
 torch.Size([2, 5, 4]),
 tensor(780))

In [18]:
A= torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

指定求和汇总张量的轴

In [19]:
A_sum_axis0 = A.sum(axis = 0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40, 45, 50, 55]), torch.Size([4]))

In [20]:
A_sum_axis1 = A.sum(axis = 1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6, 22, 38, 54, 70]), torch.Size([5]))

In [21]:
A.sum(axis = [0, 1])

tensor(190)

axis = n, 就消灭第n个维度（求和）
eg. axis = 1 (2, 5, 4)--(消灭“5”)-->(2, 4)

In [22]:
A = A.float()
A, A.mean(), A.sum() / A.numel() 

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor(9.5000),
 tensor(9.5000))

一个与求和相关的量是*平均值*(mean or average)

In [23]:
A.mean(axis = 0), A.sum(axis = 0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

计算总和或均值时保持轴数不变

In [24]:
sum_A = A.sum(axis = 1, keepdims = True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

通过广播将`A`除以`sum_A`

A / sum_A
这是逐行归一化（Row-wise normalization），
对每一行的元素除以该行的总和，使得每一行的和为 1

In [25]:
A.cumsum(axis = 0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

点积是相同位置的按元素乘积的和

In [26]:
y = torch.ones(4, dtype = torch.float32)
x, y, x * y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]),
 tensor([1., 1., 1., 1.]),
 tensor([0., 1., 2., 3.]),
 tensor(6.))

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [29]:
torch.sum(x * y), torch.dot(x, y)

(tensor(6.), tensor(6.))



### ❗不同点总结：

| 比较项             | `torch.dot(x, y)`               | `torch.sum(x * y)`                   |
|------------------|-------------------------------|-------------------------------------|
| 输入限制           | 只能用于 1D 向量                    | 任意形状（只要可广播）                    |
| 计算类型           | 向量点积（数学定义）               | 广播后的逐元素乘积再求和                    |
| 可读性             | 更清晰表达“点积”的意图              | 更通用，也可以用于矩阵或更高维度张量            |
| 支持的维度         | 只能 1D                        | 支持任意维度（广播后乘法）                    |

---

### ✅ 推荐用法建议：
- 如果明确知道 `x` 和 `y` 是一维向量，想计算点积，用 `torch.dot(x, y)`，可读性更强。
- 如果 `x` 和 `y` 是多维张量，或你不确定维度，用 `torch.sum(x * y)` 更通用、更安全。

---


矩阵向量积$Ax$是一个长度为$m$的列向量，其$i^{th}$元素是点积$a_i^Tx$

In [31]:
A, x, A.shape, x.shape, torch.mv(A, x)  #mv是matrix-vector（矩阵-向量）乘法的缩写。

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

我们可以将矩阵-矩阵乘法$AB$看作是简单地执行$m$次矩阵-向量积，并将结果拼接在一起，形成一个$n×m$矩阵

In [32]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

$L_2$范数是向量元素平方和的平方根：
$$
||x||_2 = \sqrt{\sum_{i = 1}^{n}x_i^2}
$$

In [33]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$L_1$范数,它表示向量元素的绝对值之和：
$$
||x||_1 = \sum_{i = 1}^{n}|x_i|
$$

In [34]:
torch.abs(u).sum()

tensor(7.)

矩阵的*佛罗贝尼乌斯范数*(Forbenius norm)是矩阵元素的平方和的平方根：
$$
||x||_F = \sqrt{\sum_{i = 1}^{m}\sum_{j = 1}^{n}x_i^2}
$$

In [35]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

**从数学直观、几何意义、与代码实现**几个方面讲清楚它。

---

## 📘 一、什么是 Frobenius 范数？

Frobenius 范数是一个 **衡量矩阵整体“大小”或“能量”** 的指标。

它的定义类似于向量的 L2 范数，不过对象是一个 **矩阵**：

$$
\|X\|_F = \sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n} x_{ij}^2}
$$

就是说：**把矩阵中的每个元素平方，然后加起来，最后开根号。**

---

## 📐 二、几何意义（类比向量长度）

- 对向量：
$$
  \|u\|_2 = \sqrt{u_1^2 + u_2^2 + \cdots + u_n^2}
$$
  —— 就是向量的“长度”。

- 对矩阵：
$$
  \|X\|_F = \sqrt{\text{全部元素的平方和}}
$$
  —— 可以理解为把矩阵**“铺平”成一个长向量**后，求这个长向量的长度。

👉 **所以 Frobenius 范数其实就是把矩阵看成一个大向量，计算它的 L2 范数。**

---

## 🧮 三、例子演算

比如我们有一个矩阵：

```python
X = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0]])
```

那 Frobenius 范数是：
$$
\|X\|_F = \sqrt{1^2 + 2^2 + 3^2 + 4^2} = \sqrt{1 + 4 + 9 + 16} = \sqrt{30} ≈ 5.4772
$$
在 PyTorch 中计算：
```python
torch.norm(X)  # 默认就是 Frobenius 范数
```

输出：
```python
tensor(5.4772)
```

---

## ⚙️ 四、在 PyTorch 中的使用方式

```python
X = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

torch.norm(X)               # 默认：Frobenius范数
torch.norm(X, p='fro')      # 明确指定 Frobenius 范数
torch.norm(X, p=2)          # 注意：对矩阵，p=2 会变成“谱范数”（最大奇异值），不一样
```

---

## 🎯 总结：

| 项目                 | 含义                                  |
|----------------------|---------------------------------------|
| Frobenius范数         | 矩阵所有元素平方和的平方根              |
| 几何意义             | 把矩阵当作“扁平向量”，求它的长度         |
| PyTorch 默认行为     | `torch.norm(matrix)` 默认是 Frobenius范数 |
| 与谱范数的区别        | `p=2` 对向量是 L2 范数，对矩阵是谱范数，不是 Frobenius 范数 |



## 按特定轴求和

In [39]:
import torch

a = torch.ones((2, 5, 4))
a, a.shape

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.Size([2, 5, 4]))

In [40]:
a.sum().shape  #shape为空，表示他是标量。

torch.Size([])

In [44]:
a.sum(axis = 1), a.sum(axis = 1).shape,a.sum(axis = 1, keepdims = True), a.sum(axis = 1, keepdims = True).shape

(tensor([[5., 5., 5., 5.],
         [5., 5., 5., 5.]]),
 torch.Size([2, 4]),
 tensor([[[5., 5., 5., 5.]],
 
         [[5., 5., 5., 5.]]]),
 torch.Size([2, 1, 4]))